### ISSUE TITLE
Make FamilyParser accept stream instead of path

### ISSUE THREAD

**Issue by robinandeer** [moonso/ped_parser#3]
I have a suggestion on how to make the ``FamilyParser`` class more flexible.

What if it could accept a file handle or and stream/list etc. instead of a path. This would make it more flexible when it comes to inputs. The class would just simply iterate over the lines in the general ``iterator`` object that it gets passed.

This is for example how ``yaml.load`` works out of the box :smile:

**Comment by moonso** [comment]
Nice idea! 
If i get it it could look like this:

```python
class FamilyParser(object):
  """Parses pedigree info and creates a family object with individuals."""
  def __init__(self, ped_info, family_type = 'ped', verbose=False):
    .
    .
    for line in ped_info:
      ...
```
so it only expects an iterator of any kind, right?

**Comment by robinandeer** [comment]
Thanks!

Yeah, that looks good to me. I've used file handles as iterators without calling ``readlines`` or similar.

Any sequence object with a ``__next__`` method should work ^^

**Comment by moonso** [comment]
Fixed inversion 1.4

**Comment by robinandeer** [comment]
Woho - you are alive! We miss you here but hope you are having a great time with your family :)

**Comment by moonso** [comment]
:) hope to be back tomorrow
