### ISSUE TITLE
Return instead of print?

### ISSUE THREAD

**Issue by robinandeer** [moonso/ped_parser#6]
Hi,

just thinking if it wouldn't be more flexible/intuitive to return/yield the generated string instead of printing to screen when calling ``to_madeline``:

https://github.com/moonso/ped_parser/blob/develop/ped_parser/parser.py#L540

**Comment by moonso** [comment]
Yes I agree, that is better behaviour

**Comment by moonso** [comment]
Fixed in version 1.6.1
